"""Replace ARRAY with JSON for participants and date

Revision ID: 1a305bcb59e3
Revises: 
Create Date: 2024-08-23 18:21:42.042436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1a305bcb59e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('color', sa.String(length=7), nullable=False))
    op.add_column('calendar_events', sa.Column('participants', sa.JSON(), nullable=True))
    op.alter_column('calendar_events', 'date',
               existing_type=mysql.DATETIME(),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('calendars', 'owner_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_unique_constraint(None, 'calendars', ['owner_id'])
    op.create_index(op.f('ix_storages_id'), 'storages', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_storages_id'), table_name='storages')
    op.drop_constraint(None, 'calendars', type_='unique')
    op.alter_column('calendars', 'owner_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('calendar_events', 'date',
               existing_type=sa.JSON(),
               type_=mysql.DATETIME(),
               nullable=False)
    op.drop_column('calendar_events', 'participants')
    op.drop_column('calendar_events', 'color')
    # ### end Alembic commands ###
