"""

Revision ID: 2ecc65e2e4bd
Revises: a052791facf7
Create Date: 2024-08-27 14:52:21.181314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ecc65e2e4bd'
down_revision: Union[str, None] = 'a052791facf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inbox_notification_association_ibfk_1', 'inbox_notification_association', type_='foreignkey')
    op.drop_constraint('inbox_notification_association_ibfk_2', 'inbox_notification_association', type_='foreignkey')
    op.create_foreign_key(None, 'inbox_notification_association', 'inboxes', ['inbox_id'], ['id'])
    op.create_foreign_key(None, 'inbox_notification_association', 'notifications', ['notification_id'], ['id'])
    op.add_column('notifications', sa.Column('type', sa.Enum('text', 'request'), nullable=True))
    op.add_column('notifications', sa.Column('request_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('body', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'body')
    op.drop_column('notifications', 'request_id')
    op.drop_column('notifications', 'type')
    op.drop_constraint(None, 'inbox_notification_association', type_='foreignkey')
    op.drop_constraint(None, 'inbox_notification_association', type_='foreignkey')
    op.create_foreign_key('inbox_notification_association_ibfk_2', 'inbox_notification_association', 'calendar_events', ['notification_id'], ['id'])
    op.create_foreign_key('inbox_notification_association_ibfk_1', 'inbox_notification_association', 'calendars', ['inbox_id'], ['id'])
    # ### end Alembic commands ###
