"""

Revision ID: 52fe89e87454
Revises: 8b8b33aac455
Create Date: 2024-10-30 20:46:33.327726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '52fe89e87454'
down_revision: Union[str, None] = '8b8b33aac455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_rooms', sa.Column('name', sa.String(length=100), nullable=False))
    op.alter_column('requests', 'sender_id',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'sender_id',
               existing_type=sa.Integer(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=False)
    op.drop_column('chat_rooms', 'name')
    # ### end Alembic commands ###
