"""

Revision ID: 8b8b33aac455
Revises: 0b38ca519a4e
Create Date: 2024-10-14 14:52:12.954684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b8b33aac455'
down_revision: Union[str, None] = '0b38ca519a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('sender_id', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'sender_id')
    # ### end Alembic commands ###
