"""

Revision ID: bd1045839f69
Revises: 52fe89e87454
Create Date: 2024-11-18 19:52:30.249212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bd1045839f69'
down_revision: Union[str, None] = '52fe89e87454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notes_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_index('ix_notebook_id', table_name='notebook')
    op.drop_table('notebook')
    op.drop_index('ix_notebooks_id', table_name='notebooks')
    op.drop_table('notebooks')
    op.drop_table('notebooks_notes_association')
    op.add_column('notes', sa.Column('body', sa.String(length=1000), nullable=True))
    op.add_column('notes', sa.Column('creation_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'creation_date')
    op.drop_column('notes', 'body')
    op.create_table('notebooks_notes_association',
    sa.Column('notebook_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('message_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name='notebooks_notes_association_ibfk_2'),
    sa.ForeignKeyConstraint(['notebook_id'], ['chat_rooms.id'], name='notebooks_notes_association_ibfk_1'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('notebooks',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('owner_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('creation_date', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_notebooks_id', 'notebooks', ['id'], unique=False)
    op.create_table('notebook',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('creation_date', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_notebook_id', 'notebook', ['id'], unique=False)
    op.drop_table('user_notes_association')
    # ### end Alembic commands ###
