"""

Revision ID: ed80ff19765f
Revises: 01bc7b94e5ef
Create Date: 2024-09-10 20:38:10.559037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed80ff19765f'
down_revision: Union[str, None] = '01bc7b94e5ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('type', sa.Enum('storage_request', 'friend_request', 'calendar_event_request'), nullable=True))
    op.add_column('requests', sa.Column('storage_id', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('event_id', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('friend_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('friends', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'friends')
    op.drop_column('requests', 'friend_id')
    op.drop_column('requests', 'event_id')
    op.drop_column('requests', 'storage_id')
    op.drop_column('requests', 'type')
    op.drop_column('requests', 'user_id')
    # ### end Alembic commands ###
